id: A95EEE175
title: Prayer to Avalokiteśvara
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:07:03.451101
  last_modified_at: 2022-03-01 01:07:03.451108
